pretrained_model_path: H:\AIGC\lora\controlnet\2222.ckpt
Datadir: H:\AIGC\lora\1\fill50k
ModelName: controlnet_sd15
batch_size: 1
every_n_epochs: 4
model_dir: H:\AIGC\lora\controlnet
max_epochs: 20
accumulate_grad_batches: 4
num_workers: '0'
precision: bf16
train_times: 1
shuffle: true
sampleshuffle: false
optimizer: Prodigy
safeguard_warmup: false
decouple: true
general_lr: '0.00005'
general_wd: '0'
unet_lr: '0.00005'
unet_wd: '0.000005'
text_encoder_lr: '0.00005'
text_encoder_wd: '0'
scheduler: constant_warmup
T_max: 20
T_0: 2
sd_locked: true
only_mid_control: false
num_warmup_steps: 10
logger_freq: 300
log_dir: H:\AIGC\log
log_name: '1111'
